#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Business.AimAds
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Aimit_OIS")]
	public partial class DataObjectsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAimAds_Direction(AimAds_Direction instance);
    partial void UpdateAimAds_Direction(AimAds_Direction instance);
    partial void DeleteAimAds_Direction(AimAds_Direction instance);
    partial void InsertAimAds_Group(AimAds_Group instance);
    partial void UpdateAimAds_Group(AimAds_Group instance);
    partial void DeleteAimAds_Group(AimAds_Group instance);
    partial void InsertAimAds_Item(AimAds_Item instance);
    partial void UpdateAimAds_Item(AimAds_Item instance);
    partial void DeleteAimAds_Item(AimAds_Item instance);
    #endregion
		
		public DataObjectsDataContext() : 
				base(global::AIM.Business.Properties.Settings.Default.Aimit_OISConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AimAds_Direction> AimAds_Directions
		{
			get
			{
				return this.GetTable<AimAds_Direction>();
			}
		}
		
		public System.Data.Linq.Table<AimAds_Group> AimAds_Groups
		{
			get
			{
				return this.GetTable<AimAds_Group>();
			}
		}
		
		public System.Data.Linq.Table<AimAds_Item> AimAds_Items
		{
			get
			{
				return this.GetTable<AimAds_Item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AimAds_Directions")]
	public partial class AimAds_Direction : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
		private EntitySet<AimAds_Group> _AimAds_Groups;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public AimAds_Direction()
		{
			this._AimAds_Groups = new EntitySet<AimAds_Group>(new Action<AimAds_Group>(this.attach_AimAds_Groups), new Action<AimAds_Group>(this.detach_AimAds_Groups));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AimAds_Direction_AimAds_Group", Storage="_AimAds_Groups", ThisKey="ID", OtherKey="AimAds_Direction_FK")]
		public EntitySet<AimAds_Group> AimAds_Groups
		{
			get
			{
				return this._AimAds_Groups;
			}
			set
			{
				this._AimAds_Groups.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AimAds_Groups(AimAds_Group entity)
		{
			this.SendPropertyChanging();
			entity.AimAds_Direction = this;
		}
		
		private void detach_AimAds_Groups(AimAds_Group entity)
		{
			this.SendPropertyChanging();
			entity.AimAds_Direction = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AimAds_Group")]
	public partial class AimAds_Group : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GroupID;
		
		private int _Site_FK;
		
		private string _Name;
		
		private string _ShortName;
		
		private System.Nullable<bool> _AllowScripts;
		
		private int _AimAds_Direction_FK;
		
		private string _StyleOverallClassName;
		
		private string _StyleItemClassName;
		
		private string _StyleLinkClassName;
		
		private bool _Deleted;
		
		private EntitySet<AimAds_Item> _AimAds_Items;
		
		private EntityRef<AimAds_Direction> _AimAds_Direction;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGroupIDChanging(int value);
    partial void OnGroupIDChanged();
    partial void OnSite_FKChanging(int value);
    partial void OnSite_FKChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnAllowScriptsChanging(System.Nullable<bool> value);
    partial void OnAllowScriptsChanged();
    partial void OnAimAds_Direction_FKChanging(int value);
    partial void OnAimAds_Direction_FKChanged();
    partial void OnStyleOverallClassNameChanging(string value);
    partial void OnStyleOverallClassNameChanged();
    partial void OnStyleItemClassNameChanging(string value);
    partial void OnStyleItemClassNameChanged();
    partial void OnStyleLinkClassNameChanging(string value);
    partial void OnStyleLinkClassNameChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public AimAds_Group()
		{
			this._AimAds_Items = new EntitySet<AimAds_Item>(new Action<AimAds_Item>(this.attach_AimAds_Items), new Action<AimAds_Item>(this.detach_AimAds_Items));
			this._AimAds_Direction = default(EntityRef<AimAds_Direction>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site_FK", DbType="Int NOT NULL")]
		public int Site_FK
		{
			get
			{
				return this._Site_FK;
			}
			set
			{
				if ((this._Site_FK != value))
				{
					this.OnSite_FKChanging(value);
					this.SendPropertyChanging();
					this._Site_FK = value;
					this.SendPropertyChanged("Site_FK");
					this.OnSite_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(400)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AllowScripts", DbType="Bit")]
		public System.Nullable<bool> AllowScripts
		{
			get
			{
				return this._AllowScripts;
			}
			set
			{
				if ((this._AllowScripts != value))
				{
					this.OnAllowScriptsChanging(value);
					this.SendPropertyChanging();
					this._AllowScripts = value;
					this.SendPropertyChanged("AllowScripts");
					this.OnAllowScriptsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AimAds_Direction_FK", DbType="Int NOT NULL")]
		public int AimAds_Direction_FK
		{
			get
			{
				return this._AimAds_Direction_FK;
			}
			set
			{
				if ((this._AimAds_Direction_FK != value))
				{
					if (this._AimAds_Direction.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAimAds_Direction_FKChanging(value);
					this.SendPropertyChanging();
					this._AimAds_Direction_FK = value;
					this.SendPropertyChanged("AimAds_Direction_FK");
					this.OnAimAds_Direction_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleOverallClassName", DbType="NVarChar(400)")]
		public string StyleOverallClassName
		{
			get
			{
				return this._StyleOverallClassName;
			}
			set
			{
				if ((this._StyleOverallClassName != value))
				{
					this.OnStyleOverallClassNameChanging(value);
					this.SendPropertyChanging();
					this._StyleOverallClassName = value;
					this.SendPropertyChanged("StyleOverallClassName");
					this.OnStyleOverallClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleItemClassName", DbType="NVarChar(400)")]
		public string StyleItemClassName
		{
			get
			{
				return this._StyleItemClassName;
			}
			set
			{
				if ((this._StyleItemClassName != value))
				{
					this.OnStyleItemClassNameChanging(value);
					this.SendPropertyChanging();
					this._StyleItemClassName = value;
					this.SendPropertyChanged("StyleItemClassName");
					this.OnStyleItemClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleLinkClassName", DbType="NVarChar(400)")]
		public string StyleLinkClassName
		{
			get
			{
				return this._StyleLinkClassName;
			}
			set
			{
				if ((this._StyleLinkClassName != value))
				{
					this.OnStyleLinkClassNameChanging(value);
					this.SendPropertyChanging();
					this._StyleLinkClassName = value;
					this.SendPropertyChanged("StyleLinkClassName");
					this.OnStyleLinkClassNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AimAds_Group_AimAds_Item", Storage="_AimAds_Items", ThisKey="GroupID", OtherKey="AimAds_Group_FK")]
		public EntitySet<AimAds_Item> AimAds_Items
		{
			get
			{
				return this._AimAds_Items;
			}
			set
			{
				this._AimAds_Items.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AimAds_Direction_AimAds_Group", Storage="_AimAds_Direction", ThisKey="AimAds_Direction_FK", OtherKey="ID", IsForeignKey=true)]
		public AimAds_Direction AimAds_Direction
		{
			get
			{
				return this._AimAds_Direction.Entity;
			}
			set
			{
				AimAds_Direction previousValue = this._AimAds_Direction.Entity;
				if (((previousValue != value) 
							|| (this._AimAds_Direction.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AimAds_Direction.Entity = null;
						previousValue.AimAds_Groups.Remove(this);
					}
					this._AimAds_Direction.Entity = value;
					if ((value != null))
					{
						value.AimAds_Groups.Add(this);
						this._AimAds_Direction_FK = value.ID;
					}
					else
					{
						this._AimAds_Direction_FK = default(int);
					}
					this.SendPropertyChanged("AimAds_Direction");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AimAds_Items(AimAds_Item entity)
		{
			this.SendPropertyChanging();
			entity.AimAds_Group = this;
		}
		
		private void detach_AimAds_Items(AimAds_Item entity)
		{
			this.SendPropertyChanging();
			entity.AimAds_Group = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AimAds_Item")]
	public partial class AimAds_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Title;
		
		private string _Description;
		
		private string _Href;
		
		private string _ImageFilename;
		
		private int _AimAds_Group_FK;
		
		private System.Nullable<int> _Sort;
		
		private string _LinkTarget;
		
		private bool _Deleted;
		
		private System.Nullable<System.DateTime> _DeletedDate;
		
		private System.DateTime _CreatedDate;
		
		private System.Nullable<System.DateTime> _ModifiedDate;
		
		private bool _Show;
		
		private System.Nullable<System.DateTime> _PublishFrom;
		
		private System.Nullable<System.DateTime> _PublishTo;
		
		private string _ScriptCode;
		
		private string _Border;
		
		private EntityRef<AimAds_Group> _AimAds_Group;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTitleChanging(string value);
    partial void OnTitleChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnHrefChanging(string value);
    partial void OnHrefChanged();
    partial void OnImageFilenameChanging(string value);
    partial void OnImageFilenameChanged();
    partial void OnAimAds_Group_FKChanging(int value);
    partial void OnAimAds_Group_FKChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnLinkTargetChanging(string value);
    partial void OnLinkTargetChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnDeletedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDeletedDateChanged();
    partial void OnCreatedDateChanging(System.DateTime value);
    partial void OnCreatedDateChanged();
    partial void OnModifiedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedDateChanged();
    partial void OnShowChanging(bool value);
    partial void OnShowChanged();
    partial void OnPublishFromChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishFromChanged();
    partial void OnPublishToChanging(System.Nullable<System.DateTime> value);
    partial void OnPublishToChanged();
    partial void OnScriptCodeChanging(string value);
    partial void OnScriptCodeChanged();
    partial void OnBorderChanging(string value);
    partial void OnBorderChanged();
    #endregion
		
		public AimAds_Item()
		{
			this._AimAds_Group = default(EntityRef<AimAds_Group>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Title", DbType="NVarChar(400)")]
		public string Title
		{
			get
			{
				return this._Title;
			}
			set
			{
				if ((this._Title != value))
				{
					this.OnTitleChanging(value);
					this.SendPropertyChanging();
					this._Title = value;
					this.SendPropertyChanged("Title");
					this.OnTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(MAX)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Href", DbType="NVarChar(400)")]
		public string Href
		{
			get
			{
				return this._Href;
			}
			set
			{
				if ((this._Href != value))
				{
					this.OnHrefChanging(value);
					this.SendPropertyChanging();
					this._Href = value;
					this.SendPropertyChanged("Href");
					this.OnHrefChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageFilename", DbType="NVarChar(400)")]
		public string ImageFilename
		{
			get
			{
				return this._ImageFilename;
			}
			set
			{
				if ((this._ImageFilename != value))
				{
					this.OnImageFilenameChanging(value);
					this.SendPropertyChanging();
					this._ImageFilename = value;
					this.SendPropertyChanged("ImageFilename");
					this.OnImageFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AimAds_Group_FK", DbType="Int NOT NULL")]
		public int AimAds_Group_FK
		{
			get
			{
				return this._AimAds_Group_FK;
			}
			set
			{
				if ((this._AimAds_Group_FK != value))
				{
					if (this._AimAds_Group.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnAimAds_Group_FKChanging(value);
					this.SendPropertyChanging();
					this._AimAds_Group_FK = value;
					this.SendPropertyChanged("AimAds_Group_FK");
					this.OnAimAds_Group_FKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LinkTarget", DbType="NVarChar(50)")]
		public string LinkTarget
		{
			get
			{
				return this._LinkTarget;
			}
			set
			{
				if ((this._LinkTarget != value))
				{
					this.OnLinkTargetChanging(value);
					this.SendPropertyChanging();
					this._LinkTarget = value;
					this.SendPropertyChanged("LinkTarget");
					this.OnLinkTargetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeletedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedDate
		{
			get
			{
				return this._DeletedDate;
			}
			set
			{
				if ((this._DeletedDate != value))
				{
					this.OnDeletedDateChanging(value);
					this.SendPropertyChanging();
					this._DeletedDate = value;
					this.SendPropertyChanged("DeletedDate");
					this.OnDeletedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModifiedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ModifiedDate
		{
			get
			{
				return this._ModifiedDate;
			}
			set
			{
				if ((this._ModifiedDate != value))
				{
					this.OnModifiedDateChanging(value);
					this.SendPropertyChanging();
					this._ModifiedDate = value;
					this.SendPropertyChanged("ModifiedDate");
					this.OnModifiedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Show", DbType="Bit NOT NULL")]
		public bool Show
		{
			get
			{
				return this._Show;
			}
			set
			{
				if ((this._Show != value))
				{
					this.OnShowChanging(value);
					this.SendPropertyChanging();
					this._Show = value;
					this.SendPropertyChanged("Show");
					this.OnShowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishFrom", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishFrom
		{
			get
			{
				return this._PublishFrom;
			}
			set
			{
				if ((this._PublishFrom != value))
				{
					this.OnPublishFromChanging(value);
					this.SendPropertyChanging();
					this._PublishFrom = value;
					this.SendPropertyChanged("PublishFrom");
					this.OnPublishFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PublishTo", DbType="DateTime")]
		public System.Nullable<System.DateTime> PublishTo
		{
			get
			{
				return this._PublishTo;
			}
			set
			{
				if ((this._PublishTo != value))
				{
					this.OnPublishToChanging(value);
					this.SendPropertyChanging();
					this._PublishTo = value;
					this.SendPropertyChanged("PublishTo");
					this.OnPublishToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScriptCode", DbType="NVarChar(MAX)")]
		public string ScriptCode
		{
			get
			{
				return this._ScriptCode;
			}
			set
			{
				if ((this._ScriptCode != value))
				{
					this.OnScriptCodeChanging(value);
					this.SendPropertyChanging();
					this._ScriptCode = value;
					this.SendPropertyChanged("ScriptCode");
					this.OnScriptCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Border", DbType="NVarChar(100)")]
		public string Border
		{
			get
			{
				return this._Border;
			}
			set
			{
				if ((this._Border != value))
				{
					this.OnBorderChanging(value);
					this.SendPropertyChanging();
					this._Border = value;
					this.SendPropertyChanged("Border");
					this.OnBorderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AimAds_Group_AimAds_Item", Storage="_AimAds_Group", ThisKey="AimAds_Group_FK", OtherKey="GroupID", IsForeignKey=true)]
		public AimAds_Group AimAds_Group
		{
			get
			{
				return this._AimAds_Group.Entity;
			}
			set
			{
				AimAds_Group previousValue = this._AimAds_Group.Entity;
				if (((previousValue != value) 
							|| (this._AimAds_Group.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AimAds_Group.Entity = null;
						previousValue.AimAds_Items.Remove(this);
					}
					this._AimAds_Group.Entity = value;
					if ((value != null))
					{
						value.AimAds_Items.Add(this);
						this._AimAds_Group_FK = value.GroupID;
					}
					else
					{
						this._AimAds_Group_FK = default(int);
					}
					this.SendPropertyChanged("AimAds_Group");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
