<?xml version="1.0" encoding="utf-8"?><Database Name="Congrex" Class="DataObjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=AIMITUTV3;Initial Catalog=Congrex;User ID=aimit_aim" SettingsObjectName="AIM.Business.Properties.Settings" SettingsPropertyName="CongrexConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Exhibitors" Member="Exhibitors">
    <Type Name="Exhibitor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Place" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Monter" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Site_Exhibitor" Member="Site" ThisKey="Site_FK" OtherKey="SiteID" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ConfigID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Site_Exhibitor" Member="Exhibitors" ThisKey="SiteID" OtherKey="Site_FK" Type="Exhibitor" />
      <Association Name="Site_Sponsor" Member="Sponsors" ThisKey="SiteID" OtherKey="Site_FK" Type="Sponsor" />
    </Type>
  </Table>
  <Table Name="dbo.Sponsors" Member="Sponsors">
    <Type Name="Sponsor">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Site_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="Link" Type="System.String" DbType="NVarChar(400)" CanBeNull="true" />
      <Column Name="SortOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Site_Sponsor" Member="Site" ThisKey="Site_FK" OtherKey="SiteID" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
</Database>