<?xml version="1.0" encoding="utf-8"?><Database Name="Aimit_Aim" Class="DataObjectsDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=192.168.0.3;Initial Catalog=Aimit_Aim;Persist Security Info=True;User ID=sa" SettingsObjectName="AIM.Business.Properties.Settings" SettingsPropertyName="Aimit_AimConnectionString9" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AdminRoles" Member="AdminRoles">
    <Type Name="AdminRole">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Role_AdminRole" Member="Role" ThisKey="RoleID" OtherKey="ID" Type="Role" IsForeignKey="true" />
      <Association Name="Admin_AdminRole" Member="Admin" ThisKey="AdminID" OtherKey="ID" Type="Admin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Site" Member="Sites">
    <Type Name="Site">
      <Column Name="SiteID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SiteName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Created" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ConfigID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Site_Admin" Member="Admins" ThisKey="SiteID" OtherKey="siteID" Type="Admin" />
    </Type>
  </Table>
  <Table Name="dbo.Roles" Member="Roles">
    <Type Name="Role">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Role_AdminRole" Member="AdminRoles" ThisKey="ID" OtherKey="RoleID" Type="AdminRole" />
    </Type>
  </Table>
  <Table Name="dbo.AdminLanguage" Member="AdminLanguages">
    <Type Name="AdminLanguage">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="AdminLanguage_Admin" Member="Admins" ThisKey="ID" OtherKey="AdminLanguage_FK" Type="Admin" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="siteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminLanguage_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mailNotifications" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Admin_AdminRole" Member="AdminRoles" ThisKey="ID" OtherKey="AdminID" Type="AdminRole" />
      <Association Name="AdminLanguage_Admin" Member="AdminLanguage" ThisKey="AdminLanguage_FK" OtherKey="ID" Type="AdminLanguage" IsForeignKey="true" />
      <Association Name="Site_Admin" Member="Site" ThisKey="siteID" OtherKey="SiteID" Type="Site" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.usp_GetAdministratorInGroup" Method="usp_GetAdministratorInGroup">
    <Parameter Name="AdministratorID" Parameter="administratorID" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_GetAdministratorInGroupResult">
      <Column Name="RoleID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AdminID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_GetRoleList" Method="usp_GetRoleList">
    <ElementType Name="usp_GetRoleListResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="SiteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_DeleteAdministrator" Method="usp_DeleteAdministrator">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_SaveAdministrator" Method="usp_SaveAdministrator">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FirstName" Parameter="firstName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="LastName" Parameter="lastName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="SiteID" Parameter="siteID" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_SaveAdministratorResult">
      <Column Name="Column1" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.usp_SaveAdministratorInGroup" Method="usp_SaveAdministratorInGroup">
    <Parameter Name="AdministratorID" Parameter="administratorID" Type="System.Int32" DbType="Int" />
    <Parameter Name="RoleID" Parameter="roleID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Selected" Parameter="selected" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_GetAdministrator" Method="usp_GetAdministrator">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="usp_GetAdministratorResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="firstname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lastname" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="siteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AdminLanguage_FK" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mailNotifications" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(101)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>