#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIM.Business.AimPhoto
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Aimit_Aim")]
	public partial class DataObjectsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAlbumPhoto(AlbumPhoto instance);
    partial void UpdateAlbumPhoto(AlbumPhoto instance);
    partial void DeleteAlbumPhoto(AlbumPhoto instance);
    partial void InsertAlbumPhotoInRole(AlbumPhotoInRole instance);
    partial void UpdateAlbumPhotoInRole(AlbumPhotoInRole instance);
    partial void DeleteAlbumPhotoInRole(AlbumPhotoInRole instance);
    partial void InsertAlbumPhotoCategory(AlbumPhotoCategory instance);
    partial void UpdateAlbumPhotoCategory(AlbumPhotoCategory instance);
    partial void DeleteAlbumPhotoCategory(AlbumPhotoCategory instance);
    #endregion
		
		public DataObjectsDataContext() : 
				base(global::AIM.Business.Properties.Settings.Default.Aimit_AimConnectionString3, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataObjectsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AlbumPhoto> AlbumPhotos
		{
			get
			{
				return this.GetTable<AlbumPhoto>();
			}
		}
		
		public System.Data.Linq.Table<AlbumPhotoInRole> AlbumPhotoInRoles
		{
			get
			{
				return this.GetTable<AlbumPhotoInRole>();
			}
		}
		
		public System.Data.Linq.Table<AlbumPhotoCategory> AlbumPhotoCategories
		{
			get
			{
				return this.GetTable<AlbumPhotoCategory>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_DeleteCategories")]
		public int usp_AlbumPhoto_DeleteCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_UpdateComment")]
		public int usp_AlbumPhoto_UpdateComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Comment", DbType="NVarChar(255)")] string comment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, comment);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_DeleteItem")]
		public int usp_AlbumPhoto_DeleteItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_DeleteRoles")]
		public int usp_AlbumPhoto_DeleteRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleName", DbType="NVarChar(255)")] string roleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="NVarChar(256)")] string applicationName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID, roleName, applicationName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetCategories")]
		public ISingleResult<usp_AlbumPhoto_GetCategoriesResult> usp_AlbumPhoto_GetCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjectID", DbType="Int")] System.Nullable<int> objectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), objectID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_GetCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetCategoryInfo")]
		public ISingleResult<usp_AlbumPhoto_GetCategoryInfoResult> usp_AlbumPhoto_GetCategoryInfo([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID);
			return ((ISingleResult<usp_AlbumPhoto_GetCategoryInfoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetCategoryItems")]
		public ISingleResult<usp_AlbumPhoto_GetCategoryItemsResult> usp_AlbumPhoto_GetCategoryItems([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_GetCategoryItemsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetItem")]
		public ISingleResult<usp_AlbumPhoto_GetItemResult> usp_AlbumPhoto_GetItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemID", DbType="Int")] System.Nullable<int> itemID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_GetItemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetNextItem")]
		public ISingleResult<usp_AlbumPhoto_GetNextItemResult> usp_AlbumPhoto_GetNextItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemId", DbType="Int")] System.Nullable<int> itemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemId);
			return ((ISingleResult<usp_AlbumPhoto_GetNextItemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetPreviousItem")]
		public ISingleResult<usp_AlbumPhoto_GetPreviousItemResult> usp_AlbumPhoto_GetPreviousItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemId", DbType="Int")] System.Nullable<int> itemId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemId);
			return ((ISingleResult<usp_AlbumPhoto_GetPreviousItemResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_GetRoles")]
		public ISingleResult<usp_AlbumPhoto_GetRolesResult> usp_AlbumPhoto_GetRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID);
			return ((ISingleResult<usp_AlbumPhoto_GetRolesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SaveCategory")]
		public ISingleResult<usp_AlbumPhoto_SaveCategoryResult> usp_AlbumPhoto_SaveCategory([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryName", DbType="NVarChar(255)")] string categoryName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryDate", DbType="DateTime")] System.Nullable<System.DateTime> categoryDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjectID", DbType="Int")] System.Nullable<int> objectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryComment", DbType="NVarChar(255)")] string categoryComment)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryName, categoryDate, objectID, categoryComment);
			return ((ISingleResult<usp_AlbumPhoto_SaveCategoryResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SaveItem")]
		public int usp_AlbumPhoto_SaveItem([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Filename", DbType="NVarChar(50)")] string filename, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhotoCategoryID", DbType="Int")] System.Nullable<int> photoCategoryID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), filename, photoCategoryID);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_Search")]
		public ISingleResult<usp_AlbumPhoto_SearchResult> usp_AlbumPhoto_Search([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchText", DbType="NVarChar(255)")] string searchText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjectID", DbType="Int")] System.Nullable<int> objectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchText, objectID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_SearchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SearchCategories")]
		public ISingleResult<usp_AlbumPhoto_SearchCategoriesResult> usp_AlbumPhoto_SearchCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchText", DbType="NVarChar(255)")] string searchText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjectID", DbType="Int")] System.Nullable<int> objectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchText, objectID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_SearchCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SearchComments")]
		public ISingleResult<usp_AlbumPhoto_SearchCommentsResult> usp_AlbumPhoto_SearchComments([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SearchText", DbType="NVarChar(255)")] string searchText, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ObjectID", DbType="Int")] System.Nullable<int> objectID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> roleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), searchText, objectID, roleID);
			return ((ISingleResult<usp_AlbumPhoto_SearchCommentsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SetRoles")]
		public int usp_AlbumPhoto_SetRoles([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryID", DbType="Int")] System.Nullable<int> categoryID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RoleName", DbType="NVarChar(255)")] string roleName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="NVarChar(256)")] string applicationName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), categoryID, roleName, applicationName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_SwitchPicture")]
		public int usp_AlbumPhoto_SwitchPicture([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pic_up", DbType="Int")] System.Nullable<int> pic_up, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Pic_down", DbType="Int")] System.Nullable<int> pic_down)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), pic_up, pic_down);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.usp_AlbumPhoto_UpdateCategoryComment")]
		public int usp_AlbumPhoto_UpdateCategoryComment([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ID", DbType="Int")] System.Nullable<int> iD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryName", DbType="NVarChar(255)")] string categoryName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryComment", DbType="NVarChar(255)")] string categoryComment, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AlbumCover", DbType="Int")] System.Nullable<int> albumCover)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), iD, categoryName, categoryComment, albumCover);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlbumPhoto")]
	public partial class AlbumPhoto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Filename;
		
		private int _PhotoCategoryID;
		
		private System.Nullable<int> _Sort;
		
		private string _Comment;
		
		private bool _Deleted;
		
		private EntityRef<AlbumPhotoCategory> _AlbumPhotoCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFilenameChanging(string value);
    partial void OnFilenameChanged();
    partial void OnPhotoCategoryIDChanging(int value);
    partial void OnPhotoCategoryIDChanged();
    partial void OnSortChanging(System.Nullable<int> value);
    partial void OnSortChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    #endregion
		
		public AlbumPhoto()
		{
			this._AlbumPhotoCategory = default(EntityRef<AlbumPhotoCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(50)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this.OnFilenameChanging(value);
					this.SendPropertyChanging();
					this._Filename = value;
					this.SendPropertyChanged("Filename");
					this.OnFilenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoCategoryID", DbType="Int NOT NULL")]
		public int PhotoCategoryID
		{
			get
			{
				return this._PhotoCategoryID;
			}
			set
			{
				if ((this._PhotoCategoryID != value))
				{
					if (this._AlbumPhotoCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhotoCategoryIDChanging(value);
					this.SendPropertyChanging();
					this._PhotoCategoryID = value;
					this.SendPropertyChanged("PhotoCategoryID");
					this.OnPhotoCategoryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sort", DbType="Int")]
		public System.Nullable<int> Sort
		{
			get
			{
				return this._Sort;
			}
			set
			{
				if ((this._Sort != value))
				{
					this.OnSortChanging(value);
					this.SendPropertyChanging();
					this._Sort = value;
					this.SendPropertyChanged("Sort");
					this.OnSortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AlbumPhotoCategory_AlbumPhoto", Storage="_AlbumPhotoCategory", ThisKey="PhotoCategoryID", OtherKey="ID", IsForeignKey=true)]
		public AlbumPhotoCategory AlbumPhotoCategory
		{
			get
			{
				return this._AlbumPhotoCategory.Entity;
			}
			set
			{
				AlbumPhotoCategory previousValue = this._AlbumPhotoCategory.Entity;
				if (((previousValue != value) 
							|| (this._AlbumPhotoCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AlbumPhotoCategory.Entity = null;
						previousValue.AlbumPhotos.Remove(this);
					}
					this._AlbumPhotoCategory.Entity = value;
					if ((value != null))
					{
						value.AlbumPhotos.Add(this);
						this._PhotoCategoryID = value.ID;
					}
					else
					{
						this._PhotoCategoryID = default(int);
					}
					this.SendPropertyChanged("AlbumPhotoCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlbumPhotoInRoles")]
	public partial class AlbumPhotoInRole : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _PhotoCategoryId;
		
		private System.Guid _RoleId;
		
		private EntityRef<AlbumPhotoCategory> _AlbumPhotoCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPhotoCategoryIdChanging(int value);
    partial void OnPhotoCategoryIdChanged();
    partial void OnRoleIdChanging(System.Guid value);
    partial void OnRoleIdChanged();
    #endregion
		
		public AlbumPhotoInRole()
		{
			this._AlbumPhotoCategory = default(EntityRef<AlbumPhotoCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhotoCategoryId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int PhotoCategoryId
		{
			get
			{
				return this._PhotoCategoryId;
			}
			set
			{
				if ((this._PhotoCategoryId != value))
				{
					if (this._AlbumPhotoCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnPhotoCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._PhotoCategoryId = value;
					this.SendPropertyChanged("PhotoCategoryId");
					this.OnPhotoCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this.OnRoleIdChanging(value);
					this.SendPropertyChanging();
					this._RoleId = value;
					this.SendPropertyChanged("RoleId");
					this.OnRoleIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AlbumPhotoCategory_AlbumPhotoInRole", Storage="_AlbumPhotoCategory", ThisKey="PhotoCategoryId", OtherKey="ID", IsForeignKey=true)]
		public AlbumPhotoCategory AlbumPhotoCategory
		{
			get
			{
				return this._AlbumPhotoCategory.Entity;
			}
			set
			{
				AlbumPhotoCategory previousValue = this._AlbumPhotoCategory.Entity;
				if (((previousValue != value) 
							|| (this._AlbumPhotoCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._AlbumPhotoCategory.Entity = null;
						previousValue.AlbumPhotoInRoles.Remove(this);
					}
					this._AlbumPhotoCategory.Entity = value;
					if ((value != null))
					{
						value.AlbumPhotoInRoles.Add(this);
						this._PhotoCategoryId = value.ID;
					}
					else
					{
						this._PhotoCategoryId = default(int);
					}
					this.SendPropertyChanged("AlbumPhotoCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AlbumPhotoCategory")]
	public partial class AlbumPhotoCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CategoryName;
		
		private int _ObjectID;
		
		private bool _Deleted;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private string _CategoryComment;
		
		private System.Nullable<int> _AlbumCover;
		
		private EntitySet<AlbumPhoto> _AlbumPhotos;
		
		private EntitySet<AlbumPhotoInRole> _AlbumPhotoInRoles;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoryNameChanging(string value);
    partial void OnCategoryNameChanged();
    partial void OnObjectIDChanging(int value);
    partial void OnObjectIDChanged();
    partial void OnDeletedChanging(bool value);
    partial void OnDeletedChanged();
    partial void OnCategoryDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCategoryDateChanged();
    partial void OnCategoryCommentChanging(string value);
    partial void OnCategoryCommentChanged();
    partial void OnAlbumCoverChanging(System.Nullable<int> value);
    partial void OnAlbumCoverChanged();
    #endregion
		
		public AlbumPhotoCategory()
		{
			this._AlbumPhotos = new EntitySet<AlbumPhoto>(new Action<AlbumPhoto>(this.attach_AlbumPhotos), new Action<AlbumPhoto>(this.detach_AlbumPhotos));
			this._AlbumPhotoInRoles = new EntitySet<AlbumPhotoInRole>(new Action<AlbumPhotoInRole>(this.attach_AlbumPhotoInRoles), new Action<AlbumPhotoInRole>(this.detach_AlbumPhotoInRoles));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this.OnCategoryNameChanging(value);
					this.SendPropertyChanging();
					this._CategoryName = value;
					this.SendPropertyChanged("CategoryName");
					this.OnCategoryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ObjectID", DbType="Int NOT NULL")]
		public int ObjectID
		{
			get
			{
				return this._ObjectID;
			}
			set
			{
				if ((this._ObjectID != value))
				{
					this.OnObjectIDChanging(value);
					this.SendPropertyChanging();
					this._ObjectID = value;
					this.SendPropertyChanged("ObjectID");
					this.OnObjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deleted", DbType="Bit NOT NULL")]
		public bool Deleted
		{
			get
			{
				return this._Deleted;
			}
			set
			{
				if ((this._Deleted != value))
				{
					this.OnDeletedChanging(value);
					this.SendPropertyChanging();
					this._Deleted = value;
					this.SendPropertyChanged("Deleted");
					this.OnDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this.OnCategoryDateChanging(value);
					this.SendPropertyChanging();
					this._CategoryDate = value;
					this.SendPropertyChanged("CategoryDate");
					this.OnCategoryDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryComment", DbType="NVarChar(255)")]
		public string CategoryComment
		{
			get
			{
				return this._CategoryComment;
			}
			set
			{
				if ((this._CategoryComment != value))
				{
					this.OnCategoryCommentChanging(value);
					this.SendPropertyChanging();
					this._CategoryComment = value;
					this.SendPropertyChanged("CategoryComment");
					this.OnCategoryCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this.OnAlbumCoverChanging(value);
					this.SendPropertyChanging();
					this._AlbumCover = value;
					this.SendPropertyChanged("AlbumCover");
					this.OnAlbumCoverChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AlbumPhotoCategory_AlbumPhoto", Storage="_AlbumPhotos", ThisKey="ID", OtherKey="PhotoCategoryID")]
		public EntitySet<AlbumPhoto> AlbumPhotos
		{
			get
			{
				return this._AlbumPhotos;
			}
			set
			{
				this._AlbumPhotos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="AlbumPhotoCategory_AlbumPhotoInRole", Storage="_AlbumPhotoInRoles", ThisKey="ID", OtherKey="PhotoCategoryId")]
		public EntitySet<AlbumPhotoInRole> AlbumPhotoInRoles
		{
			get
			{
				return this._AlbumPhotoInRoles;
			}
			set
			{
				this._AlbumPhotoInRoles.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_AlbumPhotos(AlbumPhoto entity)
		{
			this.SendPropertyChanging();
			entity.AlbumPhotoCategory = this;
		}
		
		private void detach_AlbumPhotos(AlbumPhoto entity)
		{
			this.SendPropertyChanging();
			entity.AlbumPhotoCategory = null;
		}
		
		private void attach_AlbumPhotoInRoles(AlbumPhotoInRole entity)
		{
			this.SendPropertyChanging();
			entity.AlbumPhotoCategory = this;
		}
		
		private void detach_AlbumPhotoInRoles(AlbumPhotoInRole entity)
		{
			this.SendPropertyChanging();
			entity.AlbumPhotoCategory = null;
		}
	}
	
	public partial class usp_AlbumPhoto_GetCategoriesResult
	{
		
		private int _ID;
		
		private string _CategoryName;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private string _CategoryComment;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_GetCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryComment", DbType="NVarChar(255)")]
		public string CategoryComment
		{
			get
			{
				return this._CategoryComment;
			}
			set
			{
				if ((this._CategoryComment != value))
				{
					this._CategoryComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetCategoryInfoResult
	{
		
		private string _CategoryName;
		
		private string _CategoryComment;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_GetCategoryInfoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryComment", DbType="NVarChar(255)")]
		public string CategoryComment
		{
			get
			{
				return this._CategoryComment;
			}
			set
			{
				if ((this._CategoryComment != value))
				{
					this._CategoryComment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetCategoryItemsResult
	{
		
		private int _ID;
		
		private string _Filename;
		
		private string _CategoryName;
		
		private string _Comment;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_GetCategoryItemsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(50)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this._Filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetItemResult
	{
		
		private int _ID;
		
		private string _Filename;
		
		private string _CategoryName;
		
		private string _Comment;
		
		private int _CID;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_GetItemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(50)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this._Filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="Int NOT NULL")]
		public int CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this._CID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetNextItemResult
	{
		
		private int _ID;
		
		public usp_AlbumPhoto_GetNextItemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetPreviousItemResult
	{
		
		private int _ID;
		
		public usp_AlbumPhoto_GetPreviousItemResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_GetRolesResult
	{
		
		private System.Guid _RoleId;
		
		private string _RoleName;
		
		public usp_AlbumPhoto_GetRolesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid RoleId
		{
			get
			{
				return this._RoleId;
			}
			set
			{
				if ((this._RoleId != value))
				{
					this._RoleId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string RoleName
		{
			get
			{
				return this._RoleName;
			}
			set
			{
				if ((this._RoleName != value))
				{
					this._RoleName = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_SaveCategoryResult
	{
		
		private System.Nullable<decimal> _Column1;
		
		public usp_AlbumPhoto_SaveCategoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Column1", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_SearchResult
	{
		
		private int _ID;
		
		private string _Filename;
		
		private string _CategoryName;
		
		private string _Comment;
		
		private int _CID;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_SearchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(50)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this._Filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="Int NOT NULL")]
		public int CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this._CID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_SearchCategoriesResult
	{
		
		private string _CategoryName;
		
		private int _ID;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_SearchCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
	
	public partial class usp_AlbumPhoto_SearchCommentsResult
	{
		
		private int _ID;
		
		private string _Filename;
		
		private string _CategoryName;
		
		private string _Comment;
		
		private int _CID;
		
		private System.Nullable<System.DateTime> _CategoryDate;
		
		private System.Nullable<int> _AlbumCover;
		
		public usp_AlbumPhoto_SearchCommentsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Filename", DbType="NVarChar(50)")]
		public string Filename
		{
			get
			{
				return this._Filename;
			}
			set
			{
				if ((this._Filename != value))
				{
					this._Filename = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryName", DbType="NVarChar(255)")]
		public string CategoryName
		{
			get
			{
				return this._CategoryName;
			}
			set
			{
				if ((this._CategoryName != value))
				{
					this._CategoryName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(255)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this._Comment = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CID", DbType="Int NOT NULL")]
		public int CID
		{
			get
			{
				return this._CID;
			}
			set
			{
				if ((this._CID != value))
				{
					this._CID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CategoryDate
		{
			get
			{
				return this._CategoryDate;
			}
			set
			{
				if ((this._CategoryDate != value))
				{
					this._CategoryDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlbumCover", DbType="Int")]
		public System.Nullable<int> AlbumCover
		{
			get
			{
				return this._AlbumCover;
			}
			set
			{
				if ((this._AlbumCover != value))
				{
					this._AlbumCover = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
